# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sumo Logic Developers
email: info@sumologic.com
description: > # this means to ignore newlines until "baseurl:"
  Download collectors, scripts, free SDKs and tools to help you troubleshoot apps in production. Use REST APIs to create custom solutions. 
baseurl: "" # the subpath of your site, e.g. /blog
repository: https://github.com/SumoLogic/sumologic.github.io
timezone: America/Los_Angeles
twitter_username: sumologic
github_username:  SumoLogic

# Build settings
markdown: kramdown

exclude:
  - README.md
  - .gitignore